services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: coingecko_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: December2003
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  airflow-db:
    image: postgres:15
    environment:
      POSTGRES_DB: airflow_db
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    volumes:
      - airflow_pgdata:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.8.1
    depends_on:
      - db
      - airflow-db
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow_db
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: coingecko_db
      DB_USER: postgres
      DB_PASSWORD: December2003
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./src:/opt/airflow/src
      - ./requirements.txt:/requirements.txt
      - ./entrypoint.sh:/entrypoint.sh
    ports:
      - "8080:8080"
    entrypoint: ["bash", "/entrypoint.sh"]

volumes:
  pgdata:
  airflow_pgdata: